# Generated by Django 5.2.4 on 2025-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
