# Generated by Django 5.2.4 on 2025-08-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_message_productview_productlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('message', 'In-app Message'), ('any', 'Any Method')], default='message', help_text='Preferred way for buyers to contact you', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.EmailField(blank=True, help_text='Contact email for this product (if different from account email)', max_length=254),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_phone',
            field=models.CharField(blank=True, help_text='Contact phone number for this product', max_length=15),
        ),
    ]
