# Generated by Django 5.2.4 on 2025-08-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_preferred_contact_method_and_more'),
    ]

    operations = [
    ]
